# Generated by Django 4.0.3 on 2022-03-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
