# Generated by Django 4.0.4 on 2022-05-07 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
