# Generated by Django 4.0.4 on 2022-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
